### ISSUE TITLE
Angular 5 Drawer Issue

### ISSUE THREAD

**Issue by RicardoVaranda** [swimlane/ngx-ui#133]
After upgrading from Angular 4 to 5, when trying to activate the drawer component we are getting the following log:

```
core.js:1350 ERROR TypeError: Cannot read property 'length' of undefined
    at InjectionService../src/index.ts.InjectionService.getRootViewContainer (index.js:41560)
    at InjectionService../src/index.ts.InjectionService.appendComponent (index.js:41652)
    at DrawerService../src/index.ts.InjectionRegisteryService.injectComponent (index.js:41719)
    at DrawerService../src/index.ts.InjectionRegisteryService.createByType (index.js:41691)
    at DrawerService../src/index.ts.InjectionRegisteryService.create (index.js:41687)
    at DrawerService../src/index.ts.DrawerService.create (index.js:44664)
    at VappInstanceCardComponent.openInfo (vapp-instance-card.component.ts:44)
    at Object.eval [as handleEvent] (VappInstanceCardComponent.ngfactory.js:89)
    at Object.handleEvent (core.js:13254)
    at Object.handleEvent (core.js:13981)
```

**Comment by marjan-georgiev** [comment]
Try upgrading to version 19.0.1

**Comment by Hypercubed** [comment]
Please reopen if you still have this issue.
